/* شخصيات حقيقية (مش في players.json) → عنوان صفحة ويكيبيديا الإنجليزية
   تُستخدم لتنزيل صور حقيقية داخل التطبيق (تشغّل offline). */
module.exports = [
  /* ---- رياضة: نجوم مش موجودين في قاعدة الـ 200 لاعب ---- */
  { arabic: 'أبو تريكة', title: 'Mohamed Aboutrika' },
  { arabic: 'تريزيجيه', title: 'Mahmoud Hassan (footballer, born 1994)' },
  { arabic: 'أحمد رفعت', title: 'Ahmed Refaat' },
  { arabic: 'محمود الخطيب', title: 'Mahmoud El Khatib' },
  { arabic: 'محمد أبو جبل', title: 'Mohamed Abou Gabal' },
  { arabic: 'ماريو بالوتيلي', title: 'Mario Balotelli' },
  { arabic: 'نور الشربيني', title: 'Nour El Sherbini' },
  { arabic: 'رامي عاشور', title: 'Rami Ashour' },
  { arabic: 'علي فرج', title: 'Ali Farag' },
  { arabic: 'إيهاب أمير', title: 'Ihab Amir' },

  /* ---- فنانين ومطربين ---- */
  { arabic: 'عمرو دياب', title: 'Amr Diab' },
  { arabic: 'تامر حسني', title: 'Tamer Hosny' },
  { arabic: 'محمد رمضان', title: 'Mohamed Ramadan (actor)' },
  { arabic: 'أحمد حلمي', title: 'Ahmed Helmy' },
  { arabic: 'كريم عبد العزيز', title: 'Karim Abdel Aziz' },
  { arabic: 'محمد منير', title: 'Mohamed Mounir' },
  { arabic: 'شيرين عبد الوهاب', title: 'Sherine' },
  { arabic: 'أنغام', title: 'Angham' },
  { arabic: 'أحمد عز', title: 'Ahmed Ezz (actor)' },
  { arabic: 'هند صبري', title: 'Hend Sabry' },
  { arabic: 'منى زكي', title: 'Mona Zaki' },
  { arabic: 'دنيا سمير غانم', title: 'Donia Samir Ghanem' },
  { arabic: 'ياسمين صبري', title: 'Yasmine Sabri' },
  { arabic: 'هاني شاكر', title: 'Hany Shaker' },
  { arabic: 'محمد حماقي', title: 'Mohamed Hamaki' },
  { arabic: 'رامي جمال', title: 'Ramy Gamal' },
  { arabic: 'أكرم حسني', title: 'Akram Hosny' },
  { arabic: 'يوسف الشريف', title: 'Youssef El Sherif' },
  { arabic: 'أحمد السقا', title: 'Ahmed El Sakka' },
  { arabic: 'نانسي عجرم', title: 'Nancy Ajram' },
  { arabic: 'إليسا', title: 'Elissa (Lebanese singer)' },
  { arabic: 'وائل كفوري', title: 'Wael Kfoury' },
  { arabic: 'راغب علامة', title: 'Ragheb Alama' },
  { arabic: 'اليسار', title: 'Mahmoud El-Lithy' },

  /* ---- مشاهير وشخصيات عالمية ---- */
  { arabic: 'ليوناردو دي كابريو', title: 'Leonardo DiCaprio' },
  { arabic: 'توم كروز', title: 'Tom Cruise' },
  { arabic: 'دواين جونسون', title: 'Dwayne Johnson' },
  { arabic: 'إيلون ماسك', title: 'Elon Musk' },
  { arabic: 'ريهانا', title: 'Rihanna' },
  { arabic: 'بيكاسو', title: 'Pablo Picasso' },
  { arabic: 'ألبرت أينشتاين', title: 'Albert Einstein' },
  { arabic: 'إسحاق نيوتن', title: 'Isaac Newton' },
  { arabic: 'نابليون بونابرت', title: 'Napoleon' },
  { arabic: 'بيل جيتس', title: 'Bill Gates' },
  { arabic: 'ستيف جوبز', title: 'Steve Jobs' },
  { arabic: 'محمد علي كلاي', title: 'Muhammad Ali' },
  { arabic: 'مايكل جوردان', title: 'Michael Jordan' },
  { arabic: 'يوسين بولت', title: 'Usain Bolt' },
  { arabic: 'تايلور سويفت', title: 'Taylor Swift' },
  { arabic: 'كليوباترا', title: 'Cleopatra' },
  { arabic: 'شارلي شابلن', title: 'Charlie Chaplin' },
  { arabic: 'فان جوخ', title: 'Vincent van Gogh' },
];